version: "2"

services:
  vpn:
    image: kylemanna/openvpn
    restart: unless-stopped
    container_name: ovpn
    env_file: .env
    ports:
      - "${PORT}:1194/udp"
    volumes:
      - ./ovpn_data:/etc/openvpn
    cap_add:
      - NET_ADMIN
    logging:
      driver: "json-file"
      options:
        max-size: "20M"
        max-file: "10"
